### ISSUE TITLE
| ?- ++Error[XSB/Runtime/P]: [Existence (No procedure usermod : vulExists / 3 exists)] []

### ISSUE THREAD

**Issue by zuozijiZHOULI** [fiware-cybercaptor/mulval#4]
| ?- ++Error[XSB/Runtime/P]: [Existence (No procedure usermod : vulExists / 3 exists)] []
Forward Continuation...
... machine:xsb_backtrace/1  From /home/zhouli/software/attractgrapetools/XSB/syslib/machine.xwam
... standard:call_c/1  From /home/zhouli/software/attractgrapetools/XSB/syslib/standard.xwam
... standard:call/1  From /home/zhouli/software/attractgrapetools/XSB/syslib/standard.xwam
... setof:bfindall/4  From /home/zhouli/software/attractgrapetools/XSB/syslib/setof.xwam
... setof:bagof1/3  From /home/zhouli/software/attractgrapetools/XSB/syslib/setof.xwam
... setof:setof/3  From /home/software/attractgrapetools/XSB/syslib/setof.xwam
... standard:call/1  From /home/software/attractgrapetools/XSB/syslib/standard.xwam
... setof:findall/3  From /home/software/attractgrapetools/XSB/syslib/setof.xwam
... x_interp:_$call/1  From /home/software/attractgrapetools/XSB/syslib/x_interp.xwam
... x_interp:call_query/1  From /home/software/attractgrapetools/XSB/syslib/x_interp.xwam
... standard:call/1  From /home/software/attractgrapetools/XSB/syslib/standard.xwam
... standard:catch/3  From /home/software/attractgrapetools/XSB/syslib/standard.xwam
... x_interp:interpreter/0  From /home/software/attractgrapetools/XSB/syslib/x_interp.xwam
... loader:ll_code_call/3  From /home/software/attractgrapetools/XSB/syslib/loader.xwam
... loader:load_object_file/2  From /home/zhouli/software/attractgrapetools/XSB/syslib/loader.xwam
... standard:call/1  From /home/software/attractgrapetools/XSB/syslib/standard.xwam
... standard:catch/3  From /home/software/attractgrapetools/XSB/syslib/standard.xwam
| ?- ++Error[XSB/Runtime/P]: [Existence (No procedure usermod : networkServiceInfo / 5 exists)] []
Forward Continuation...
... machine:xsb_backtrace/1  From /home/software/attractgrapetools/XSB/syslib/machine.xwam
... standard:call/1  From /home/software/attractgrapetools/XSB/syslib/standard.xwam
... standard:call_c/1  From /home/software/attractgrapetools/XSB/syslib/standard.xwam

**Comment by farrukh43** [comment]
Have you found the solution? If yes please share it.

**Comment by yukunren** [comment]
大神 找到解决方案了吗 如果有解决方案 麻烦分享一下 可好  谢谢
